name: 自動化

on:
  schedule:
    - cron: "0 5,17 * * *"
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@955fb50215ce7f039f2642136b341db9603e38e1 
        with:
          modules: "login,ad_handler,sign,report,guild,report,answer,report,lottery,report,logout,report,telegram"
          parameters: ${{ secrets.parameters || '{}' }}
          secrets: ${{ secrets.secrets }}
